### PR TITLE
Translation in C#

### PR DESCRIPTION
**Pull request by boucardbruno**
Hi Emily,

As I said @NCrafts, I translated java files into C #.

It's a first attempt. 

But before going further, I prefer to exchange with you.

@brunoboucard

### CODE REVIEW

**Comment by emilybache** [comment]
Thanks! This is a great help. I would like to tweak a few things - make some of the classes use properties instead of Java style accessors for example. I think I can fix that quite easily based on this though!

**Comment by emilybache** [comment]
so I just pushed a couple of things adding on what you've done. What remains now is to translate the branch 'with_tests'. You'll need to use Approvals (http://approvaltests.com/). Would you like to do that?

**Comment by boucardbruno** [comment]
> Owner
>     
> 
> 
>   
> 
> 
>   
> 
> 
>     
>       
> 
>   emilybache
>   
> 
>     
> 
>     commented
> 
> 
>       2 hours ago
> 
> 
>     
>     
>   
> 
> 
> 
>     
> 
>       
> 
> 
>   
>     
>       
>           so I just pushed a couple of things adding on what you've done. What remains now is to translate the branch 'with_tests'. You'll need to use Approvals (http://approvaltests.com/). Would you like to do that?

Hi Emily, I used ApprovalTest in the branch with_tests.

**Comment by emilybache** [comment]
That's great! Unfortunately I think you have missed pushing your changes to with_tests? I can't see any changes in that branch in your repo on github.

**Comment by boucardbruno** [comment]
Indeed, I forgot to synchronize the branch. I copy you the code because I am without good connection networks.
 
using System;
using System.Collections.Generic;
using ApprovalTests;
using ApprovalTests.Reporters;
using Xunit;

namespace StarterProject
{
    [UseReporter(typeof(DiffReporter))]
    public class MessageEnricherTest
    {
        private Exception VLookup()
        {
            return new Exception("Object reference not set to an instance of an object");
        }

        [Fact]
        private void CircularReference()
        {
            var enricher = new MessageEnricher();
            var worksheet = new SpreadsheetWorkbook();

            Exception e = new SpreadsheetException("Circular Reference", new List<string> {"C4", "C5"}, null);

            Approvals.Verify(enricher.EnrichError(worksheet, e));
        }

        [Fact]
        private void CircularReferenceWrongException()
        {
            var enricher = new MessageEnricher();
            var worksheet = new SpreadsheetWorkbook();

            var e = new Exception("Circular Reference");

            Approvals.Verify(enricher.EnrichError(worksheet, e));
        }

        [Fact]
        private void ExpressionParseException()
        {
            var enricher = new MessageEnricher();
            var worksheet = new SpreadsheetWorkbook();

            Exception e = new ExpressionParseException();

            Approvals.Verify(enricher.EnrichError(worksheet, e));
        }


        [Fact]
        private void NoEnrichmentNeeded()
        {
            var enricher = new MessageEnricher();
            var worksheet = new SpreadsheetWorkbook();

            var e = new Exception("Terrible problem");

            Approvals.Verify(enricher.EnrichError(worksheet, e));
        }

        [Fact]
        private void NoMatchesFound()
        {
            var enricher = new MessageEnricher();
            var worksheet = new SpreadsheetWorkbook();

            Exception e = new SpreadsheetException("No matches found", null, "Missing Token");

            Approvals.Verify(enricher.EnrichError(worksheet, e));
        }

        [Fact]
        private void NoMatchesFoundWrongException()
        {
            var enricher = new MessageEnricher();
            var worksheet = new SpreadsheetWorkbook();

            var e = new Exception("No matches found");

            Approvals.Verify(enricher.EnrichError(worksheet, e));
        }

        [Fact]
        private void ObjectReferenceNotSet()
        {
            var enricher = new MessageEnricher();
            var worksheet = new SpreadsheetWorkbook();

            var e = VLookup();

            Approvals.Verify(enricher.EnrichError(worksheet, e));
        }

        [Fact]
        private void ObjectReferenceNotSetButStacktraceNotVLookup()
        {
            var enricher = new MessageEnricher();
            var worksheet = new SpreadsheetWorkbook();

            var e = new Exception("Object reference not set to an instance of an object");

            Approvals.Verify(enricher.EnrichError(worksheet, e));
        }
    }
}

Tonight I will have more time to integrate it on the last repo.

**Pull request merged**
